### ISSUE TITLE
cloud cluster db about Host key verification failed

### ISSUE THREAD

**Issue by Wushigang915** [OpenVisualCloud/Smart-City-Sample#602]
hi
when i Multiple Cluster Setup, the bd and web log is not normal,it's about Host key verification failed

![image](https://user-images.githubusercontent.com/68258570/90715523-1408eb00-e2dd-11ea-91de-8f8526b8e864.png)

**Comment by xwu2git** [comment]
Please try the latest master code. The path has a typo. It should be `/etc/hostkey/known_hosts`.

**Comment by Wushigang915** [comment]
> Please try the latest master code. The path has a typo. It should be `/etc/hostkey/known_hosts`.

thanks a lot.  this issue has been solved. i have another question about db in edge cluster.
![image](https://user-images.githubusercontent.com/68258570/90841627-a9fd4e00-e38f-11ea-967e-235995233158.png)
and Will it affect others?

**Comment by xwu2git** [comment]
Your edge node db cannot start because the connection to the master is not found. 
Have you started the cloud cluster? 
Please send the full logs of the edge db.

**Comment by Wushigang915** [comment]
> Your edge node db cannot start because the connection to the master is not found.
> Have you started the cloud cluster?
> Please send the full logs of the edge db.

you remind me ,i excute " ssh -4 -f -N -L localhost:29300:localhost:29300 root@ip" in the db pod, this is db log
![image](https://user-images.githubusercontent.com/68258570/90845257-46c3e980-e398-11ea-8d3f-639962bd6e08.png)
Does this mean that edge db started normally? but the bd-init still running, not completed

**Comment by xwu2git** [comment]
Almost, it's progressing. There are multiple reverse and forward tunnels that must be created. See deployment/kubernetes/helm/smtc/templates/office-db.yaml. 

But why you need to do it manually? The helm script setup those tunnels automatically.

**Comment by Wushigang915** [comment]
> Almost, it's progressing. There are multiple reverse and forward tunnels that must be created. See deployment/kubernetes/helm/smtc/templates/office-db.yaml.
> 
> But why you need to do it manually? The helm script setup those tunnels automatically.

 I have no idea, the office-storage have issue too and others pod is normal. 
![image](https://user-images.githubusercontent.com/68258570/91004574-29e11d80-e607-11ea-999c-359c4ae146f8.png)

**Comment by xwu2git** [comment]
What user do you use to build and run the sample?
It's a permission issue. The complain is about the host-key permission 0440 too wide.
Strange I did not see those in our testing.

**Comment by xwu2git** [comment]
Double checking. Do you use the latest master or the release version v20.7?   
Please make sure you completely rebuild the sample and `make tunnels`.

**Comment by Wushigang915** [comment]
> Double checking. Do you use the latest master or the release version v20.7?
> Please make sure you completely rebuild the sample and `make tunnels`.

I use the 131155e6c364f201958ad18d68daf767387ba1c8 and Commits on Aug 14, 2020.
 it‘s mean the  permission issue have an impact? this picture is log about office-upload when i run the sample in last week, it have the same issue,But it does not seem to affect the next operation
![image](https://user-images.githubusercontent.com/68258570/91006593-5f3c3a00-e60c-11ea-9c10-22082d359394.png)

**Comment by xwu2git** [comment]
The permission must be set correctly for the tunnels to work.
I submitted a fix to the master branch. Please try it.
If you build and run as a regular user, the mode must be 0440. 
If you build and run as root, the mode must be 0400.

**Comment by Wushigang915** [comment]
> The permission must be set correctly for the tunnels to work.
> I submitted a fix to the master branch. Please try it.
> If you build and run as a regular user, the mode must be 0440.
> If you build and run as root, the mode must be 0400.

ok, I will have a try, and the cloud-web and cloud-storage have the same  permission issue

**Comment by Wushigang915** [comment]
> > The permission must be set correctly for the tunnels to work.
> > I submitted a fix to the master branch. Please try it.
> > If you build and run as a regular user, the mode must be 0440.
> > If you build and run as root, the mode must be 0400.
> 
> ok, I will have a try, and the cloud-web and cloud-storage have the same permission issue

i change the mode to 0400 , but the cloud-web and cloud-storage still have permission issue , i build and run as root. 
![image](https://user-images.githubusercontent.com/68258570/91031283-f1573900-e632-11ea-958d-2edaf36ba4c3.png)

and then i use  the latest master code, still have the issue in cloud-web and storage
![image](https://user-images.githubusercontent.com/68258570/91031568-5c087480-e633-11ea-976f-1ad34379b166.png)

**Comment by xwu2git** [comment]
The security context: fsgroup interferes with the defaultMode setting, when the user is a root.
Fixed on master. Please try it.

**Comment by Wushigang915** [comment]
> The security context: fsgroup interferes with the defaultMode setting, when the user is a root.
> Fixed on master. Please try it.

I use  the latest master,  but the edge-db still not work. this log about edge-db
[edge-db log.txt](https://github.com/OpenVisualCloud/Smart-City-Sample/files/5121687/edge-db.log.txt)

Unless I execute the command in the db pod.

**Comment by Wushigang915** [comment]
> The security context: fsgroup interferes with the defaultMode setting, when the user is a root.
> Fixed on master. Please try it.

I use the latest master code. and edge-upload has the issue. this is the log of upload
[edge-upload log.txt](https://github.com/OpenVisualCloud/Smart-City-Sample/files/5121883/edge-upload.log.txt)

and the ssh forward in the edge is not stable, sometimes the pod must be restarted several times to succeed

**Comment by xwu2git** [comment]
Can you send me the cloud-storage logs?

**Comment by Wushigang915** [comment]
> Can you send me the cloud-storage logs?

cloud-storage logs
[cloud-storage.txt](https://github.com/OpenVisualCloud/Smart-City-Sample/files/5127095/cloud-storage.txt)

edge-storage logs
[edge-storage.txt](https://github.com/OpenVisualCloud/Smart-City-Sample/files/5127097/edge-storage.txt)
